plugins {
    id 'com.android.application' version '8.7.3'
}

android {
    namespace 'pl.bartek.layzspa'
    compileSdk 35

    defaultConfig {
        applicationId 'pl.bartek.layzspa'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1'
    }

    sourceSets {
        main {
            java.srcDirs = ['.']
            manifest.srcFile 'AndroidManifest.xml'
            res.srcDirs = []
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
