package pl.bartek.layzspa;

import android.content.*;import android.content.res.ColorStateList;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import com.google.android.material.button.MaterialButton;import com.google.android.material.textfield.*;import org.json.JSONObject;import java.util.concurrent.TimeUnit;import okhttp3.*;

public class MainActivity extends AppCompatActivity{
 final int BG=Color.rgb(11,16,22),PANEL=Color.rgb(18,25,33),PANEL2=Color.rgb(22,31,40),TEXT=Color.rgb(239,246,252),MUTED=Color.rgb(145,163,178),BLUE=Color.rgb(69,196,255),GREEN=Color.rgb(99,230,190),RED=Color.rgb(255,104,104); final Handler h=new Handler(Looper.getMainLooper()); final OkHttpClient client=new OkHttpClient.Builder().pingInterval(20,TimeUnit.SECONDS).build(); WebSocket ws; boolean closing; String ip="192.168.1.40"; int target,heat,pump,air,jets,power; TextView status,temp,targetV,info,rssi; TextInputEditText ipEdit; MaterialButton connect,heatB,pumpB,airB,jetsB,powerB;
 TextView tv(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(0,4,0,4);return v;} GradientDrawable gd(int c,float r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(r);return d;} LinearLayout box(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;} LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;} MaterialButton btn(String s){MaterialButton b=new MaterialButton(this);b.setText(s);b.setAllCaps(false);b.setTextSize(15);b.setTypeface(Typeface.DEFAULT,1);b.setTextColor(TEXT);b.setCornerRadius(18);b.setStrokeWidth(1);b.setStrokeColor(ColorStateList.valueOf(Color.rgb(45,61,74)));b.setBackgroundTintList(ColorStateList.valueOf(PANEL2));b.setMinHeight(0);b.setMinimumHeight(0);return b;}
 void half(LinearLayout r,View v,int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,86,1);p.setMargins(0,0,m,0);r.addView(v,p);} LinearLayout section(String s){LinearLayout l=box();l.setPadding(18,14,18,18);l.setBackground(gd(PANEL,22));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,12,0,0);l.setLayoutParams(p);TextView t=tv(s.toUpperCase(),12,MUTED);t.setTypeface(Typeface.DEFAULT,1);t.setLetterSpacing(.12f);l.addView(t);return l;}
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(Color.rgb(8,12,17));ip=getPreferences(0).getString("ip",ip);ui();connect();}
 void ui(){ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.setBackgroundColor(BG);LinearLayout root=box();root.setPadding(18,16,18,28);sv.addView(root);LinearLayout head=row();TextView t=tv("LAY-Z-SPA",26,TEXT);t.setTypeface(Typeface.DEFAULT,1);head.addView(t,new LinearLayout.LayoutParams(0,54,1));head.addView(tv("v0.2",12,MUTED),new LinearLayout.LayoutParams(-2,54));root.addView(head);
 LinearLayout st=row();st.setPadding(14,0,14,0);st.setBackground(gd(PANEL,18));status=tv("●  ROZŁĄCZONO",13,RED);status.setTypeface(Typeface.DEFAULT,1);st.addView(status,new LinearLayout.LayoutParams(0,46,1));root.addView(st);
 LinearLayout ir=row();TextInputLayout til=new TextInputLayout(this);til.setHint("Adres IP ESP8266");til.setHintTextColor(ColorStateList.valueOf(MUTED));til.setBoxBackgroundMode(TextInputLayout.BOX_BACKGROUND_OUTLINE);til.setBoxCornerRadii(16,16,16,16);til.setBoxStrokeColor(Color.rgb(45,61,74));ipEdit=new TextInputEditText(this);ipEdit.setText(ip);ipEdit.setTextColor(TEXT);ipEdit.setTextSize(15);til.addView(ipEdit);ir.addView(til,new LinearLayout.LayoutParams(0,62,1));connect=btn("Połącz");LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(112,62);cp.setMargins(10,0,0,0);ir.addView(connect,cp);root.addView(ir);connect.setOnClickListener(v->{ip=ipEdit.getText()==null?"":ipEdit.getText().toString().trim();getPreferences(0).edit().putString("ip",ip).apply();connect();});
 LinearLayout card=box();card.setGravity(Gravity.CENTER_HORIZONTAL);card.setPadding(20,22,20,20);card.setBackground(gd(PANEL,26));LinearLayout.LayoutParams cpl=new LinearLayout.LayoutParams(-1,220);cpl.setMargins(0,14,0,0);root.addView(card,cpl);TextView lab=tv("AKTUALNA TEMPERATURA",12,MUTED);lab.setTypeface(Typeface.DEFAULT,1);lab.setLetterSpacing(.1f);card.addView(lab);temp=tv("--°C",54,TEXT);temp.setGravity(17);temp.setTypeface(Typeface.DEFAULT,1);card.addView(temp,new LinearLayout.LayoutParams(-1,92));targetV=tv("CEL  --°C",15,BLUE);targetV.setGravity(17);targetV.setTypeface(Typeface.DEFAULT,1);card.addView(targetV);
 LinearLayout tr=row();MaterialButton minus=btn("−"),plus=btn("+");half(tr,minus,8);half(tr,plus,0);root.addView(tr);minus.setOnClickListener(v->setTarget(target-1));plus.setOnClickListener(v->setTarget(target+1));
 LinearLayout controls=section("Sterowanie");root.addView(controls);LinearLayout r1=row();heatB=btn("GRZANIE\nOFF");pumpB=btn("POMPA / FILTR\nOFF");half(r1,heatB,8);half(r1,pumpB,0);controls.addView(r1);LinearLayout r2=row();jetsB=btn("HYDROJET\nOFF");airB=btn("BĄBELKI\nOFF");half(r2,jetsB,8);half(r2,airB,0);LinearLayout.LayoutParams r2p=new LinearLayout.LayoutParams(-1,86);r2p.setMargins(0,8,0,0);controls.addView(r2,r2p);powerB=btn("ZASILANIE  •  OFF");LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,74);pp.setMargins(0,8,0,0);controls.addView(powerB,pp);heatB.setOnClickListener(v->toggle(3,heat));pumpB.setOnClickListener(v->toggle(4,pump));airB.setOnClickListener(v->toggle(2,air));jetsB.setOnClickListener(v->toggle(11,jets));powerB.setOnClickListener(v->toggle(25,power));
 LinearLayout sys=section("System");root.addView(sys);info=tv("Model: --\nFirmware: --\nIP: --",14,TEXT);sys.addView(info);rssi=tv("RSSI: -- dBm",13,MUTED);sys.addView(rssi);setContentView(sv);}
 void stateBtn(MaterialButton b,String s,int x){boolean on=x==1;b.setText(s+"\n"+(on?"ON":"OFF"));b.setTextColor(on?Color.rgb(8,18,23):TEXT);b.setBackgroundTintList(ColorStateList.valueOf(on?GREEN:PANEL2));b.setStrokeColor(ColorStateList.valueOf(on?GREEN:Color.rgb(45,61,74)));} void power(){boolean on=power==1;powerB.setText("ZASILANIE  •  "+(on?"ON":"OFF"));powerB.setTextColor(on?Color.rgb(8,18,23):TEXT);powerB.setBackgroundTintList(ColorStateList.valueOf(on?BLUE:PANEL2));}
 void setTarget(int x){if(target==0)return;send(0,Math.max(20,Math.min(40,x)));} void toggle(int c,int s){send(c,s==1?0:1);} void send(int c,int v){if(ws==null){toast("Brak połączenia z ESP8266");return;}try{JSONObject o=new JSONObject();o.put("CMD",c);o.put("VALUE",v);o.put("XTIME",0);o.put("INTERVAL",0);o.put("TXT","");ws.send(o.toString());}catch(Exception e){toast("Błąd polecenia");}}
 void connect(){if(ip.isEmpty())return;closing=false;if(ws!=null)ws.close(1000,"reconnect");setStatus("●  ŁĄCZENIE");Request q=new Request.Builder().url("ws://"+ip+":81/").build();ws=client.newWebSocket(q,new WebSocketListener(){public void onOpen(WebSocket w,Response r){runOnUiThread(()->{setStatus("●  POŁĄCZONO");connect.setText("Połączono");});}public void onMessage(WebSocket w,String s){parse(s);}public void onFailure(WebSocket w,Throwable e,Response r){runOnUiThread(()->{setStatus("●  BRAK POŁĄCZENIA");connect.setText("Połącz");});if(!closing)later();}public void onClosed(WebSocket w,int c,String s){if(!closing)later();}});}
 void later(){h.removeCallbacksAndMessages(null);h.postDelayed(this::connect,3000);} void parse(String s){try{JSONObject o=new JSONObject(s);String c=o.optString("CONTENT");if("STATES".equals(c)){target=o.optInt("TGT",0);int tm=o.optInt("TMP",0);heat=o.optInt("GRN",0);pump=o.optInt("FLT",0);air=o.optInt("AIR",0);jets=o.optInt("HJT",0);power=o.optInt("PWR",0);runOnUiThread(()->{temp.setText(tm+"°C");targetV.setText("CEL  "+target+"°C");stateBtn(heatB,"GRZANIE",heat);stateBtn(pumpB,"POMPA / FILTR",pump);stateBtn(jetsB,"HYDROJET",jets);stateBtn(airB,"BĄBELKI",air);power();});}else if("OTHER".equals(c)){String m=o.optString("MODEL","--"),f=o.optString("FW","--"),i=o.optString("IP",ip);int r=o.optInt("RSSI",0);runOnUiThread(()->{info.setText("Model: "+m+"\nFirmware: "+f+"\nIP: "+i);rssi.setText("RSSI: "+r+" dBm");});}}catch(Exception ignored){}}
 void setStatus(String s){if(status==null)return;status.setText(s);status.setTextColor(s.contains("POŁĄCZONO")?GREEN:s.contains("ŁĄCZENIE")?BLUE:RED);}void toast(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_SHORT).show());}@Override protected void onDestroy(){closing=true;h.removeCallbacksAndMessages(null);if(ws!=null)ws.close(1000,"app close");client.dispatcher().executorService().shutdown();super.onDestroy();}
}
