plugins { id 'com.android.application' }
android { namespace 'pl.bartek.layzspa'; compileSdk 35
 defaultConfig { applicationId 'pl.bartek.layzspa'; minSdk 26; targetSdk 35; versionCode 41; versionName '0.3.1' }
}
dependencies { implementation 'androidx.appcompat:appcompat:1.7.0'; implementation 'com.google.android.material:material:1.12.0'; implementation 'com.squareup.okhttp3:okhttp:4.12.0' }
